definitions:
  steps:
    - step: &run-tests
        name: Running test
        image: golang:1.14-alpine
        script:
          - export CGO_ENABLED=0
          - go test -cover ./...
        caches:
          - gomodules
  caches:
    gomodules: $GOPATH/pkg/mod
pipelines:
  branches:
    '**':
      - parallel:
          - step: *run-tests
          - step:
              name: Running linter
              image: golangci/golangci-lint:v1.27-alpine
              script:
                - export CGO_ENABLED=0
                - golangci-lint run --color always --disable-all -E gofmt -E deadcode -E errcheck -E gosimple -E govet -E ineffassign -E staticcheck -E structcheck -E typecheck -E varcheck